# .github/workflows/build.yml
name: build-and-push

on:
  workflow_dispatch:
    inputs:
      upstream_tag:
        description: "Base n8n tag (e.g., latest or 1.64.0)"
        required: false
        default: "latest"
  schedule:
    - cron: "0 3 * * 1"   # 毎週月曜 03:00 UTC に再ビルド（任意）
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set tags
        id: meta
        run: |
          TAG="${{ github.event.inputs.upstream_tag || 'latest' }}"
          echo "UPSTREAM_TAG=$TAG" >> $GITHUB_OUTPUT
          # 付与するタグ（latest固定＋ベース追従タグ）
          # 例: localworks/n8n:latest, localworks/n8n:n8n-1.64.0
          if [ "$TAG" = "latest" ]; then
            echo "IMAGE_TAGS=localworks/n8n:latest" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAGS=localworks/n8n:latest,localworks/n8n:n8n-$TAG" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            UPSTREAM_TAG=${{ steps.meta.outputs.UPSTREAM_TAG }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.IMAGE_TAGS }}
          cache-from: type=registry,ref=localworks/n8n:buildcache
          cache-to: type=registry,ref=localworks/n8n:buildcache,mode=max
